<?php
/*
 * DHC2 TRAIT RARITY -- derived from chain, not invented.
 *
 * tier comes from how many of the 226 minted DHC2 Fighters actually wore the
 * trait, read from the CIP-25 metadata under policy
 * b31a34ca2b08bfc905d2b630c9317d148554303fa7f0d605fd651cb5 via Koios:
 *
 *     10+ fighters  common      6-9  uncommon     3-5  epic
 *     1-2 fighters  legendary   none mythic
 *
 * 'mythic' therefore means the art exists but no minted Fighter uses it --
 * trait art that never made it into the collection.
 *
 * rate is the drop chance WITHIN ITS CATEGORY, so each category sums to 100%.
 * It is a designed curve rather than the on-chain frequency: 44/28/17/9/2 per
 * tier, split evenly among that category's traits of that tier, so the tier
 * label is what decides the odds. A category missing a tier spreads that
 * share over the tiers it does have.
 *
 * count is kept alongside so any rate can be traced back to the chain.
 * Regenerate rather than hand-edit if the collection ever changes.
 */
return array(
	'arms' => array(
		'connected-protector-limbs' => array('uncommon', 6, 9.52),
		'cyber-666-knight-armor' => array('epic', 4, 3.47),
		'cyber-inferno-limbs' => array('legendary', 2, 1.15),
		'deflektor' => array('uncommon', 6, 9.52),
		'deteriorated-mk100-blaster-arms' => array('legendary', 2, 1.15),
		'dh-pilot' => array('legendary', 2, 1.15),
		'golden-cyborg-limbs' => array('legendary', 1, 1.15),
		'head-chopper' => array('legendary', 1, 1.15),
		'infested-robo-limb' => array('epic', 3, 3.47),
		'influenza-blaster-3k' => array('epic', 3, 3.47),
		'mk100-blaster-arms' => array('legendary', 1, 1.15),
		'perforator-arm-replacement' => array('epic', 5, 3.47),
		'robo-crusher-arms' => array('common', 11, 44.9),
		'silver-cyborg-limbs' => array('epic', 3, 3.47),
		'skeletal-stabber' => array('legendary', 1, 1.15),
		'symbio-flexx' => array('uncommon', 7, 9.52),
		'turret-blue-cyborg-limbs' => array('legendary', 1, 1.15),
	),
	'background' => array(
		'advanced-circuit-1' => array('uncommon', 8, 2.8),
		'advanced-circuit-2' => array('epic', 3, 1.7),
		'black' => array('common', 0, 4.89),
		'bright-red' => array('common', 0, 4.89),
		'dark-explosion' => array('legendary', 2, 1.29),
		'data-tunnel' => array('epic', 4, 1.7),
		'dh-aracnyd-web' => array('uncommon', 9, 2.8),
		'dh-killer-bubbles' => array('legendary', 2, 1.29),
		'dh-landscape' => array('legendary', 1, 1.29),
		'dh-nebula-02' => array('epic', 4, 1.7),
		'dh-nebula-1' => array('epic', 3, 1.7),
		'dh-nebula-3' => array('legendary', 1, 1.29),
		'dh-thunder' => array('epic', 5, 1.7),
		'digital-abyss' => array('legendary', 1, 1.29),
		'digital-flames-1' => array('epic', 5, 1.7),
		'digital-flames-2' => array('common', 10, 4.89),
		'digital-trap-01' => array('uncommon', 6, 2.8),
		'digital-trap-03' => array('epic', 3, 1.7),
		'digital-trap-04' => array('uncommon', 7, 2.8),
		'digital-trap-2' => array('uncommon', 7, 2.8),
		'eon-raider-spacecraft-window' => array('mythic', 0, 0.33),
		'exoplanet-landscape' => array('mythic', 0, 0.33),
		'experimentation-facility-entrance' => array('epic', 3, 1.7),
		'hellscape' => array('uncommon', 7, 2.8),
		'light-blue' => array('common', 0, 4.89),
		'light-green' => array('common', 0, 4.89),
		'light-purple' => array('common', 0, 4.89),
		'light-yellow' => array('common', 0, 4.89),
		'quasar-tf-39-sun' => array('uncommon', 6, 2.8),
		'red' => array('common', 0, 4.89),
		'white' => array('common', 0, 4.89),
		'wormhole-passage' => array('legendary', 2, 1.29),
		'xlon-ddos-attack' => array('uncommon', 9, 2.8),
		'xlon-s-2yk-attack-01' => array('epic', 4, 1.7),
		'xlon-s-2yk-attack-02' => array('epic', 3, 1.7),
		'xlon-s-building-trap' => array('mythic', 0, 0.33),
		'xlon-s-digital-smoke-attack' => array('legendary', 2, 1.29),
		'xlon-s-disintegrating-bubbles' => array('mythic', 0, 0.33),
		'xlon-s-optical-attack' => array('mythic', 0, 0.33),
		'xlon-s-psi-attack' => array('uncommon', 6, 2.8),
		'xlons-building-interior' => array('mythic', 0, 0.33),
		'xlons-s-complex' => array('uncommon', 8, 2.8),
	),
	'companion' => array(
		'arachnid-laser-cannon' => array('epic', 5, 6.3),
		'code-sea-predator' => array('legendary', 2, 8.33),
		'dh-vision-shoulder-cam' => array('uncommon', 7, 25.93),
		'golden-isopunk' => array('legendary', 2, 8.33),
		'mk100-insekt' => array('epic', 5, 6.3),
		'silver-isopunk' => array('epic', 5, 6.3),
		'threat-seeker-antenna' => array('epic', 3, 6.3),
		'u-vigilance-device-1' => array('uncommon', 6, 25.93),
		'u-vigilance-device-2' => array('epic', 3, 6.3),
	),
	'effects' => array(
		'2yk-flames' => array('mythic', 0, 0.67),
		'cyber-lava-attack' => array('common', 16, 8.8),
		'cyber-sparks' => array('epic', 4, 3.4),
		'dhc2-comic-cover-1' => array('common', 10, 8.8),
		'dhc2-comic-cover-2' => array('uncommon', 7, 5.6),
		'dhc2-comic-cover-3' => array('uncommon', 8, 5.6),
		'digi-goo-trap' => array('legendary', 1, 3.0),
		'digital-666-smoke' => array('epic', 5, 3.4),
		'digital-bubbles-1' => array('epic', 5, 3.4),
		'digital-bubbles-2' => array('uncommon', 8, 5.6),
		'digital-bubbles-3' => array('epic', 3, 3.4),
		'digital-fire' => array('common', 10, 8.8),
		'dissolving-code-attack' => array('uncommon', 6, 5.6),
		'electricity' => array('mythic', 0, 0.67),
		'lava-thunder-attack' => array('common', 12, 8.8),
		'love-demonstration' => array('mythic', 0, 0.67),
		'virtual-smoke' => array('legendary', 1, 3.0),
		'xlon-digi-fire-attack' => array('uncommon', 8, 5.6),
		'xlon-s-black-fire-attack' => array('epic', 5, 3.4),
		'xlon-s-chamber-destruction' => array('common', 10, 8.8),
		'xlon-s-code-attack' => array('legendary', 1, 3.0),
	),
	'head' => array(
		'alien-zombie' => array('legendary', 2, 1.0),
		'alien-zombie-02' => array('uncommon', 6, 3.11),
		'beheaded-cyborg' => array('common', 11, 4.89),
		'broken-xlon-repeater' => array('legendary', 1, 1.0),
		'broken-xlon-repeater-1' => array('legendary', 1, 1.0),
		'c73' => array('uncommon', 9, 3.11),
		'cyborg-stryker' => array('common', 13, 4.89),
		'cyborg-stryker-02' => array('common', 10, 4.89),
		'cyborg-stryker-03' => array('epic', 4, 2.83),
		'dh-alien-punk' => array('uncommon', 8, 3.11),
		'dh-cop-01' => array('epic', 4, 2.83),
		'dh-cop-03' => array('common', 12, 4.89),
		'dh-cop-03-1' => array('common', 12, 4.89),
		'dh-cop-2' => array('legendary', 2, 1.0),
		'dh-demon' => array('epic', 4, 2.83),
		'dh-zombie' => array('legendary', 1, 1.0),
		'gas-mask' => array('uncommon', 6, 3.11),
		'golden-cyborg' => array('epic', 5, 2.83),
		'happy-cyborg-decoy' => array('epic', 3, 2.83),
		'inferno-wasp-guardian' => array('legendary', 2, 1.0),
		'mk100' => array('common', 10, 4.89),
		'mk100-torso' => array('mythic', 0, 1.0),
		'mk200' => array('uncommon', 6, 3.11),
		'mk300' => array('epic', 4, 2.83),
		'mutant-goblin' => array('mythic', 0, 1.0),
		'planet-1kz-killer-alien' => array('legendary', 1, 1.0),
		'planet-8tz-specter' => array('legendary', 2, 1.0),
		'planet-8tz-specter-1' => array('legendary', 2, 1.0),
		'predator' => array('uncommon', 7, 3.11),
		'sentinel' => array('common', 21, 4.89),
		'silver-cyborg' => array('uncommon', 7, 3.11),
		'u-e-mutant-01' => array('uncommon', 8, 3.11),
		'u-e-mutant-02' => array('common', 11, 4.89),
		'v12-punk-raider' => array('uncommon', 9, 3.11),
		'xbot' => array('common', 12, 4.89),
	),
	'headgear' => array(
		'666-demon-headgear' => array('legendary', 1, 0.9),
		'alien-predator' => array('legendary', 1, 0.9),
		'alien-skull' => array('epic', 4, 1.42),
		'arachno-neural-implant' => array('epic', 3, 1.42),
		'bio-circuit-head-port' => array('legendary', 2, 0.9),
		'code-prisoner-helmet' => array('epic', 3, 1.42),
		'cyber-insekt-helmet' => array('epic', 3, 1.42),
		'cyber-knight-helmet' => array('epic', 3, 1.42),
		'cyber-purr-helmet' => array('common', 10, 44.0),
		'cyber-voodoo' => array('mythic', 0, 0.4),
		'cyber-voodoo-1' => array('mythic', 0, 0.4),
		'damaged-mk100-scuba-headgear' => array('legendary', 1, 0.9),
		'dh-destroyer' => array('legendary', 2, 0.9),
		'dh-fire-goggles' => array('legendary', 2, 0.9),
		'dh-sorceror' => array('legendary', 1, 0.9),
		'dm-mask' => array('epic', 5, 1.42),
		'e-pharaoh-head' => array('mythic', 0, 0.4),
		'golden-cyber-plague-detecting-mask' => array('epic', 5, 1.42),
		'killer-phantom-mask' => array('legendary', 1, 0.9),
		'malware-detecting-mask' => array('uncommon', 6, 9.33),
		'merged' => array('mythic', 0, 0.4),
		'mk100-codesea-explorer-helmet' => array('epic', 4, 1.42),
		'mk100-scuba-headgear' => array('legendary', 1, 0.9),
		'mk200-cyber-plague-vr-mask' => array('epic', 5, 1.42),
		'red-cyborg-helmet' => array('uncommon', 8, 9.33),
		'saber-tech-headgear' => array('uncommon', 7, 9.33),
		'steel-viking-helmet' => array('mythic', 0, 0.4),
		'superbug-3' => array('epic', 4, 1.42),
		'trojan-detection-mask' => array('epic', 4, 1.42),
		'ww2-helmet' => array('legendary', 2, 0.9),
		'xlon-implant' => array('epic', 3, 1.42),
	),
	'torso' => array(
		'amplified-dreadnought' => array('common', 10, 6.04),
		'bone-robot' => array('common', 15, 6.04),
		'c-4589-mechanic' => array('uncommon', 9, 2.37),
		'c38' => array('common', 10, 6.04),
		'c73' => array('uncommon', 7, 2.37),
		'cyber-venom-predator' => array('uncommon', 8, 2.37),
		'data-explorer' => array('uncommon', 6, 2.37),
		'dh-alien-punk' => array('epic', 4, 6.23),
		'dh-cop' => array('common', 21, 6.04),
		'dh-cop-2' => array('common', 10, 6.04),
		'dynamo' => array('uncommon', 7, 2.37),
		'golden-cyborg' => array('uncommon', 7, 2.37),
		'inferno-wasp-guardian' => array('epic', 4, 6.23),
		'mk100' => array('uncommon', 6, 2.37),
		'mk200' => array('uncommon', 8, 2.37),
		'nebula-demon' => array('uncommon', 8, 2.37),
		'planet-8tz-specter' => array('uncommon', 7, 2.37),
		'planet-p-386-punk' => array('mythic', 0, 2.2),
		'red-cyborg' => array('uncommon', 6, 2.37),
		'silver-cyborg' => array('uncommon', 7, 2.37),
		'skeletal-robot' => array('common', 14, 6.04),
		't39-planet-alien-flesh' => array('common', 14, 6.04),
		'v12-raider' => array('common', 10, 6.04),
		'virtual-raider' => array('epic', 3, 6.23),
		'zx350-centinel' => array('uncommon', 8, 2.37),
	),
	'weapon' => array(
		'annihilation-belt' => array('common', 11, 14.97),
		'axe' => array('epic', 5, 1.93),
		'bioweapon' => array('legendary', 2, 3.06),
		'dh-raider-equipment' => array('epic', 4, 1.93),
		'dh-spike-blaster' => array('legendary', 1, 3.06),
		'dh-spike-blaster-1' => array('legendary', 1, 3.06),
		'electric-morning-star' => array('epic', 3, 1.93),
		'lil-fren' => array('common', 10, 14.97),
		'lil-fren-1' => array('common', 10, 14.97),
		'mega-taser-cannon' => array('epic', 3, 1.93),
		'mega-taser-cannon-1' => array('epic', 3, 1.93),
		'plastic-blaster' => array('uncommon', 6, 28.57),
		'scythe' => array('epic', 4, 1.93),
		'scythe-sash' => array('epic', 4, 1.93),
		'skull-krusher' => array('epic', 4, 1.93),
		'skull-krusher-sash' => array('epic', 4, 1.93),
	),
);
